package middleware

import (
	"net/url"
	"strings"
	"sync"

	"github.com/bestruirui/octopus/internal/model"
	"github.com/bestruirui/octopus/internal/op"
	"github.com/bestruirui/octopus/internal/utils/log"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
)

// corsAllowHeaders 枚举实际用到的请求头。凭证模式下 "*" 不符合 Fetch 规范
// (浏览器要求逐项匹配)，所以这里显式列出而不是通配。
var corsAllowHeaders = []string{
	"Authorization",
	"Content-Type",
	"Accept",
	"x-api-key",
	"x-goog-api-key",
	"x-goog-api-client",
	"anthropic-version",
	"anthropic-beta",
	"anthropic-dangerous-direct-browser-access",
	"OpenAI-Beta",
	"OpenAI-Organization",
	"OpenAI-Project",
	// OpenAI and Anthropic's browser SDKs are generated by Stainless and add
	// these diagnostic headers to cross-origin requests.
	"x-stainless-lang",
	"x-stainless-package-version",
	"x-stainless-os",
	"x-stainless-arch",
	"x-stainless-runtime",
	"x-stainless-runtime-version",
	"x-stainless-retry-count",
	"x-stainless-timeout",
	"x-stainless-async",
	"x-stainless-helper-method",
	"x-stainless-poll-helper",
	"x-stainless-custom-poll-interval",
	"x-stainless-read-timeout",
	"x-stainless-raw-response",
	"x-stainless-multipart",
}

// corsSchemelessWarned 保证「配置项缺少 scheme」的告警对同一个值只打一次，
// 避免每个跨域请求都刷屏。键是配置里的原始字符串，条目数受配置长度约束。
var corsSchemelessWarned sync.Map

func corsBaseConfig() cors.Config {
	config := cors.DefaultConfig()
	config.AllowMethods = []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}
	config.AllowHeaders = corsAllowHeaders
	config.ExposeHeaders = []string{"Content-Disposition"}
	return config
}

// Cors 按运行时设置在两套策略之间分发:
//   - 为空: 不允许跨域
//   - "*": 允许所有来源，但**不下发凭证** —— 通配 + 凭证会让任意站点用用户的
//     cookie 发起跨域请求，浏览器规范本身也禁止这个组合
//   - 逗号分隔的完整 origin 列表: 只允许指定来源，可携带凭证
func Cors() gin.HandlerFunc {
	// 通配模式: 回显字面量 "*"，凭证强制关闭。
	wildcardConfig := corsBaseConfig()
	wildcardConfig.AllowAllOrigins = true
	wildcardConfig.AllowCredentials = false
	wildcard := cors.New(wildcardConfig)

	// 白名单模式: 逐项匹配来源，允许携带凭证。
	allowlistConfig := corsBaseConfig()
	allowlistConfig.AllowCredentials = true
	allowlistConfig.AllowOriginFunc = corsOriginAllowed
	allowlist := cors.New(allowlistConfig)

	return func(c *gin.Context) {
		if corsAllowOriginsSetting() == "*" {
			wildcard(c)
			return
		}
		allowlist(c)
	}
}

func corsAllowOriginsSetting() string {
	allowed, err := op.SettingGetString(model.SettingKeyCORSAllowOrigins)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(allowed)
}

// corsOriginAllowed 比较归一化后的 origin。只在白名单模式下调用。
func corsOriginAllowed(origin string) bool {
	allowed := corsAllowOriginsSetting()
	if allowed == "" || allowed == "*" {
		return false
	}

	wantOrigin, ok := normalizeOrigin(origin)
	if !ok {
		return false
	}

	for _, item := range strings.Split(allowed, ",") {
		item = strings.TrimSpace(item)
		if item == "" {
			continue
		}
		candidate, ok := normalizeOrigin(item)
		if !ok {
			warnSchemelessCORSEntry(item)
			continue
		}
		if candidate == wantOrigin {
			return true
		}
	}
	return false
}

// normalizeOrigin 把 origin 归一化成小写的 scheme://host[:port]，并去掉与
// scheme 对应的默认端口，便于逐字比较。
//
// 缺少 scheme 的配置项一律拒绝: 只写 "example.com" 会同时放行 http:// 和
// https://，等于把明文来源也纳入白名单。
func normalizeOrigin(raw string) (string, bool) {
	raw = strings.TrimSpace(raw)
	raw = strings.TrimRight(raw, "/")
	if raw == "" {
		return "", false
	}

	parsed, err := url.Parse(raw)
	if err != nil {
		return "", false
	}

	scheme := strings.ToLower(parsed.Scheme)
	if scheme != "http" && scheme != "https" {
		return "", false
	}

	host := strings.ToLower(parsed.Host)
	if host == "" {
		return "", false
	}
	// origin 里不该出现 path/query/fragment 之外的内容；带路径的配置项按前缀匹配
	// 会引入歧义，直接忽略路径部分即可。
	if (scheme == "http" && strings.HasSuffix(host, ":80")) ||
		(scheme == "https" && strings.HasSuffix(host, ":443")) {
		host = host[:strings.LastIndex(host, ":")]
	}

	return scheme + "://" + host, true
}

func warnSchemelessCORSEntry(item string) {
	if _, loaded := corsSchemelessWarned.LoadOrStore(item, struct{}{}); loaded {
		return
	}
	log.Warnf("cors: ignoring allow-origin entry %q, a full origin with scheme is required (e.g. https://%s)", item, item)
}
