#!/usr/bin/env python3
"""
从 https://models.dev/api.json 获取 LLM 价格数据，
生成 internal/price/presets.go 文件
"""

import json
import re
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

LLM_PRICE_URL = "https://models.dev/api.json"

PROVIDERS = [
    "openai",      # GPT 系列
    "anthropic",   # Claude 系列
    "google",      # Gemini 系列
    "deepseek",    # DeepSeek 系列
    "xai",         # Grok 系列
    "alibaba",     # Qwen 系列
    "zhipuai",     # GLM 系列
    "minimax",     # MiniMax 系列
    "moonshotai",  # Kimi/Moonshot
    "v0",          # v0 系列
]

# 其他模型别名映射 (非 Claude)
MODEL_ALIASES: dict[str, list[str]] = {
    # 在这里添加其他模型的别名
}

PRESETS_GO_TEMPLATE = '''package price

// Code generated by scripts/updatePrice.py. DO NOT EDIT.
// Last updated: {update_time}

import (
	"sync"

	"github.com/bestruirui/octopus/internal/model"
)

var llmPriceLock sync.RWMutex

var llmPrice = map[string]model.LLMPrice{{
{entries}
}}
'''


def fetch_price_data() -> dict:
    """从 API 获取价格数据"""
    req = urllib.request.Request(
        LLM_PRICE_URL, 
        headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"}
    )
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read().decode("utf-8"))


def format_price(value: float | None) -> str:
    """格式化价格值，去除不必要的尾部零"""
    if value is None:
        return "0"
    if value == 0:
        return "0"
    # 使用 repr 避免浮点数精度问题，然后去除尾部零
    formatted = f"{value:.10f}".rstrip("0").rstrip(".")
    return formatted


def generate_claude_aliases(model_id: str) -> list[str]:
    """
    为 Claude 模型自动生成别名
    
    规则:
    1. claude-{type}-{major}-{minor}[-suffix] -> claude-{type}-{major}.{minor}[-suffix]
       例: claude-opus-4-5 -> claude-opus-4.5
    2. claude-{type}-{major}-{minor}[-suffix] -> claude-{major}.{minor}-{type}[-suffix]
       例: claude-opus-4-5 -> claude-4.5-opus
    3. claude-{major}-{minor}-{type}[-suffix] -> claude-{major}.{minor}-{type}[-suffix]
       例: claude-3-5-sonnet-20241022 -> claude-3.5-sonnet-20241022
    """
    if not model_id.startswith("claude-"):
        return []
    
    aliases = []
    
    # 模式1: claude-{type}-{major}-{minor}[-suffix]
    # 匹配: claude-opus-4-5, claude-opus-4-5-20251101, claude-sonnet-4-0, claude-haiku-4-5
    # 注意: minor 版本号只能是单个数字，避免把日期当成版本号
    pattern1 = re.compile(r"^claude-(opus|sonnet|haiku)-(\d)-(\d)(-.*)?$")
    match1 = pattern1.match(model_id)
    if match1:
        model_type = match1.group(1)
        major = match1.group(2)
        minor = match1.group(3)
        suffix = match1.group(4) or ""
        
        # 别名1: claude-{type}-{major}.{minor}[-suffix]
        alias1 = f"claude-{model_type}-{major}.{minor}{suffix}"
        aliases.append(alias1)
        
        # 别名2: claude-{major}.{minor}-{type}[-suffix]
        alias2 = f"claude-{major}.{minor}-{model_type}{suffix}"
        aliases.append(alias2)
        
        # 别名3: claude-{major}-{minor}-{type}[-suffix]
        alias3 = f"claude-{major}-{minor}-{model_type}{suffix}"
        aliases.append(alias3)
        
        return aliases
    
    # 模式2: claude-{major}-{minor}-{type}[-suffix]
    # 匹配: claude-3-5-sonnet-20241022, claude-3-7-sonnet-latest, claude-3-5-haiku-20241022
    # 注意: major/minor 版本号只能是单个数字
    pattern2 = re.compile(r"^claude-(\d)-(\d)-(opus|sonnet|haiku)(-.*)?$")
    match2 = pattern2.match(model_id)
    if match2:
        major = match2.group(1)
        minor = match2.group(2)
        model_type = match2.group(3)
        suffix = match2.group(4) or ""
        
        # 别名1: claude-{major}.{minor}-{type}[-suffix]
        alias1 = f"claude-{major}.{minor}-{model_type}{suffix}"
        aliases.append(alias1)
        
        # 别名2: claude-{type}-{major}.{minor}[-suffix]
        alias2 = f"claude-{model_type}-{major}.{minor}{suffix}"
        aliases.append(alias2)
        
        return aliases
    
    return aliases


def generate_entry(model_id: str, cost: dict) -> str:
    """生成单个模型的 Go map entry"""
    input_price = format_price(cost.get("input"))
    output_price = format_price(cost.get("output"))
    cache_read = format_price(cost.get("cache_read"))
    cache_write = format_price(cost.get("cache_write"))

    return f'\t"{model_id}": {{Input: {input_price}, Output: {output_price}, CacheRead: {cache_read}, CacheWrite: {cache_write}}},'


def unique_aliases(aliases: list[str]) -> list[str]:
    """按生成顺序对别名去重，并统一转换为小写。"""
    return list(dict.fromkeys(alias.lower() for alias in aliases if alias))


def collect_price_entries(
    raw_price: dict,
    providers: list[str] | None = None,
    model_aliases: dict[str, list[str]] | None = None,
) -> tuple[dict[str, dict], dict[str, int], list[str]]:
    """收集唯一模型条目；重复 key 按 provider 顺序由后者覆盖前者。"""
    providers = PROVIDERS if providers is None else providers
    model_aliases = MODEL_ALIASES if model_aliases is None else model_aliases

    entries: dict[str, dict] = {}
    provider_counts = {provider: 0 for provider in providers}
    warnings = []

    def add_entry(model_id: str, cost: dict, provider: str, source_model_id: str) -> None:
        previous = entries.get(model_id)
        if previous is not None:
            warnings.append(
                f'Duplicate model ID "{model_id}": '
                f'{previous["provider"]}/{previous["source_model_id"]} overwritten by '
                f'{provider}/{source_model_id}'
            )
            provider_counts[previous["provider"]] -= 1
            # Reinsert the key so generated order also follows the winning provider.
            del entries[model_id]

        entries[model_id] = {
            "cost": cost,
            "provider": provider,
            "source_model_id": source_model_id,
        }
        provider_counts[provider] += 1

    for provider in providers:
        provider_data = raw_price.get(provider)
        if provider_data is None:
            continue

        for model_data in provider_data.get("models", {}).values():
            source_model_id = model_data.get("id") or ""
            model_id = source_model_id.lower()
            if not model_id:
                continue

            cost = model_data.get("cost") or {}
            add_entry(model_id, cost, provider, source_model_id)

            aliases = generate_claude_aliases(model_id)
            aliases.extend(model_aliases.get(model_id, []))
            for alias in unique_aliases(aliases):
                add_entry(alias, cost, provider, source_model_id)

    return entries, provider_counts, warnings


def render_presets(entries: dict[str, dict], update_time: str) -> str:
    """将唯一模型条目渲染为 presets.go。"""
    return PRESETS_GO_TEMPLATE.format(
        update_time=update_time,
        entries="\n".join(
            generate_entry(model_id, entry["cost"])
            for model_id, entry in entries.items()
        ),
    )


def main():
    print(f"Fetching price data from {LLM_PRICE_URL}...")
    raw_price = fetch_price_data()
    entries, provider_counts, warnings = collect_price_entries(raw_price)

    for provider in PROVIDERS:
        if provider not in raw_price:
            print(f"  Provider '{provider}' not found, skipping...")
            continue
        print(f"  {provider}: {provider_counts[provider]} models")

    for warning in warnings:
        print(f"  Warning: {warning}")

    update_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    content = render_presets(entries, update_time)

    script_dir = Path(__file__).parent
    output_path = script_dir.parent / "internal" / "price" / "presets.go"

    output_path.write_text(content, encoding="utf-8")
    print(f"\nGenerated {output_path} with {len(entries)} models")


if __name__ == "__main__":
    main()
