package model

import (
	"encoding/json"
	"errors"
)

// Message represents a message in the conversation.
type Message struct {
	Role string `json:"role,omitempty"`
	// Content of the message.
	// string or []ContentPart, be careful about the omitzero tag, it required.
	// Some framework may depended on the behavior, we should not response the field if not present.
	Content MessageContent `json:"content,omitzero"`
	Name    *string        `json:"name,omitempty"`

	// The refusal message generated by the model.
	Refusal string `json:"refusal,omitempty"`

	// For tool call response.

	// The index of the message that the tool call is associated with.
	// Is is a help field, will not be sent to the llm service.
	MessageIndex *int    `json:"-"`
	ToolCallID   *string `json:"tool_call_id,omitempty"`
	// The name of the tool call.
	// Is is a help field, will not be sent to the llm service.
	ToolCallName *string `json:"-"`
	// This field is a help field, will not be sent to the llm service.
	ToolCallIsError *bool      `json:"-"`
	ToolCalls       []ToolCall `json:"tool_calls,omitempty"`

	// Images is used by some providers (e.g., Gemini via OpenAI compat) for image generation responses.
	// Images will be merged into Content.MultipleContent during response processing.
	Images []MessageContentPart `json:"images,omitempty"`

	Audio *struct {
		Data       string `json:"data,omitempty"`
		ExpiresAt  int64  `json:"expires_at,omitempty"`
		ID         string `json:"id,omitempty"`
		Transcript string `json:"transcript,omitempty"`
	} `json:"audio,omitempty"`

	// This property is used for the "reasoning" feature supported by deepseek-reasoner
	// the doc from deepseek:
	// - https://api-docs.deepseek.com/api/create-chat-completion#responses
	ReasoningContent *string `json:"reasoning_content,omitempty"`

	// Reasoning is used by some providers (e.g., OpenRouter, Ollama cloud) as an alternative to ReasoningContent.
	// Both fields serve the same purpose, use GetReasoningContent() to get the value.
	Reasoning *string `json:"reasoning,omitempty"`

	// Help field, will not be sent to the llm service, to adapt the anthropic think signature.
	// Deprecated: prefer ReasoningBlocks for multi-block provenance. Kept as a fallback so that
	// legacy single-block emitters (OpenRouter, Ollama compat) keep working.
	ReasoningSignature *string `json:"reasoning_signature,omitempty"`

	// ReasoningSignatureSource is the authoritative provenance for the legacy
	// flat ReasoningSignature mirror. Provider-specific outbounds must only
	// replay signatures whose source matches their provider.
	ReasoningSignatureSource *OpaqueSignature `json:"-"`

	// RedactedThinkingBlocks stores opaque redacted_thinking blocks from Anthropic.
	// Deprecated: mirrored into ReasoningBlocks with Kind=ReasoningBlockKindRedacted. Kept for
	// backward compatibility with callers that read this field directly.
	RedactedThinkingBlocks []string `json:"-"`

	// ReasoningBlocks preserves the full order of thinking / redacted_thinking / signature blocks
	// from the assistant turn. Each entry carries its provider-specific signature verbatim so that
	// multi-turn tool-use scenarios (Anthropic extended thinking, Gemini 3 thoughtSignature) can be
	// replayed to the upstream without signature_mismatch / FAILED_PRECONDITION errors.
	ReasoningBlocks []ReasoningBlock `json:"-"`

	// ProviderExtensions stores provider-specific message hints. It is internal-only.
	ProviderExtensions *ProviderExtensions `json:"-"`

	// CacheControl is used for provider-specific cache control (e.g., Anthropic).
	// This field is not serialized in JSON.
	CacheControl *CacheControl `json:"-"`
}

func (m *Message) ClearHelpFields() {
	m.ReasoningSignature = nil
	m.ReasoningSignatureSource = nil
	m.RedactedThinkingBlocks = nil
	m.ReasoningBlocks = nil
}

// Normalize prepares the message for dispatch to upstream providers. It
// performs two jobs:
//  1. Drop empty text parts from MultipleContent. Image / audio / file /
//     tool_use / tool_result / thinking parts are preserved verbatim.
//  2. If the message ends up with no content-carrying payload at all
//     (no text, no non-text parts, no tool_calls, no reasoning), insert a
//     single-space placeholder into Content.Content. This matches
//     Anthropic's strictest requirement — empty assistant / user messages
//     elicit a 400 — while remaining harmless for OpenAI and Gemini.
//
// Normalize is idempotent and safe to call before every outbound dispatch.
func (m *Message) Normalize() {
	if m == nil {
		return
	}

	if len(m.Content.MultipleContent) > 0 {
		filtered := m.Content.MultipleContent[:0]
		for _, part := range m.Content.MultipleContent {
			if isEmptyTextPart(part) {
				continue
			}
			filtered = append(filtered, part)
		}
		m.Content.MultipleContent = filtered
	}

	if m.hasAnyPayload() {
		return
	}

	space := " "
	m.Content.Content = &space
	m.Content.MultipleContent = nil
}

// hasAnyPayload reports whether the message carries any information that
// would reach the upstream provider. Used by Normalize to decide whether
// the single-space placeholder is necessary.
func (m *Message) hasAnyPayload() bool {
	if m.Content.Content != nil && *m.Content.Content != "" {
		return true
	}
	if len(m.Content.MultipleContent) > 0 {
		return true
	}
	if len(m.ToolCalls) > 0 {
		return true
	}
	if m.ToolCallID != nil && *m.ToolCallID != "" {
		return true
	}
	if m.ReasoningContent != nil && *m.ReasoningContent != "" {
		return true
	}
	if m.Reasoning != nil && *m.Reasoning != "" {
		return true
	}
	if len(m.ReasoningBlocks) > 0 {
		return true
	}
	if len(m.RedactedThinkingBlocks) > 0 {
		return true
	}
	return false
}

// isEmptyTextPart reports whether a MessageContentPart is a text-type entry
// whose Text is nil or empty. Non-text parts always return false so image /
// audio / file / tool_use payloads are never dropped.
func isEmptyTextPart(p MessageContentPart) bool {
	if p.Type != "" && p.Type != "text" {
		return false
	}
	return p.Text == nil || *p.Text == ""
}

// GetReasoningContent returns the reasoning content from either ReasoningContent or Reasoning field.
// Different providers use different field names for the same purpose.
func (m *Message) GetReasoningContent() string {
	if m.ReasoningContent != nil {
		return *m.ReasoningContent
	}
	if m.Reasoning != nil {
		return *m.Reasoning
	}
	return ""
}

// SetReasoningContent sets the reasoning content to the ReasoningContent field.
func (m *Message) SetReasoningContent(s string) {
	m.ReasoningContent = &s
}

type MessageContent struct {
	Content         *string              `json:"content,omitempty"`
	MultipleContent []MessageContentPart `json:"multiple_content,omitempty"`
}

func (c MessageContent) MarshalJSON() ([]byte, error) {
	if len(c.MultipleContent) > 0 {
		if len(c.MultipleContent) == 1 && c.MultipleContent[0].Type == "text" {
			return json.Marshal(c.MultipleContent[0].Text)
		}

		return json.Marshal(c.MultipleContent)
	}

	return json.Marshal(c.Content)
}

func (c *MessageContent) UnmarshalJSON(data []byte) error {
	var str string

	err := json.Unmarshal(data, &str)
	if err == nil {
		c.Content = &str
		return nil
	}

	var parts []MessageContentPart

	err = json.Unmarshal(data, &parts)
	if err == nil {
		c.MultipleContent = parts
		return nil
	}

	return errors.New("invalid content type")
}

// MessageContentPart represents different types of content (text, image, etc.)
type MessageContentPart struct {
	// Type is the type of the content part.
	// e.g. "text", "image_url", "input_audio", "file", "document",
	// "server_tool_use", "server_tool_result".
	Type string `json:"type"`
	// Text is the text content, required when type is "text"
	Text *string `json:"text,omitempty"`

	// ImageURL is the image URL content, required when type is "image_url"
	ImageURL *ImageURL `json:"image_url,omitempty"`

	// Audio is the audio content, required when type is "input_audio"
	Audio *Audio `json:"input_audio,omitempty"`

	// File is the file content, required when type is "file"
	File *File `json:"file,omitempty"`

	// Document is the document content, required when type is "document".
	// Mirrors Anthropic's document block — carries a PDF/text source plus
	// optional title/context metadata and citation hints. The json:"-" tag
	// keeps the block from leaking to OpenAI chat completions (which would
	// reject the field); provider-specific outbound paths read the Go
	// field directly.
	Document *DocumentSource `json:"-"`

	// ServerToolUse captures an Anthropic server_tool_use block (e.g.
	// web_search_20250305, code_execution_20250522) so it can be preserved
	// across retries and re-emitted verbatim. Non-Anthropic providers drop
	// the block and surface a warning. json:"-" for the same reason as
	// Document.
	ServerToolUse *ServerToolUseBlock `json:"-"`

	// ServerToolResult captures the result payload returned by Anthropic
	// after a server-side tool invocation (web_search_tool_result,
	// code_execution_tool_result). Shape mirrors tool_result but uses the
	// dedicated server_* name so routing logic can distinguish them.
	// json:"-" for the same reason as Document.
	ServerToolResult *ServerToolResultBlock `json:"-"`

	// ProviderExtensions stores provider-specific content-part hints. It is internal-only.
	ProviderExtensions *ProviderExtensions `json:"-"`

	// CacheControl is used for provider-specific cache control (e.g., Anthropic).
	// This field is not serialized in JSON.
	CacheControl *CacheControl `json:"-"`
}

// DocumentSource mirrors the Anthropic document content block. A document
// carries a source (base64 / url / text / content array) plus optional
// title / context / citation metadata. Other providers that don't support
// native documents fall back to emitting either an inline PDF blob (Gemini
// inline_data application/pdf) or a text hint in the user turn.
type DocumentSource struct {
	// Type identifies the envelope: "base64", "url", "text", or "content".
	// "content" carries an array of sub-blocks (not yet fully supported —
	// passthrough only).
	Type string `json:"type"`

	// MediaType is the MIME type of the document payload.
	// Examples: "application/pdf", "text/plain".
	MediaType string `json:"media_type,omitempty"`

	// Data is the base64-encoded document (when Type=="base64").
	Data string `json:"data,omitempty"`

	// URL is the document URL (when Type=="url").
	URL string `json:"url,omitempty"`

	// Text is the raw text content (when Type=="text"). Providers that
	// cannot embed documents natively use this as the fallback payload.
	Text string `json:"text,omitempty"`

	// Content holds pre-chunked sub-blocks (when Type=="content"). This is
	// an opaque JSON payload — we preserve it for Anthropic passthrough but
	// do not interpret it.
	Content json.RawMessage `json:"content,omitempty"`

	// Title / Context are optional metadata hints Anthropic surfaces in
	// citation responses. Both are passed through unchanged.
	Title   string `json:"title,omitempty"`
	Context string `json:"context,omitempty"`

	// Citations configures Anthropic's citation generation. When Enabled
	// is true the model may emit citation references to this document.
	Citations *DocumentCitations `json:"citations,omitempty"`
}

// DocumentCitations matches Anthropic's document.citations sub-object.
type DocumentCitations struct {
	Enabled bool `json:"enabled,omitempty"`
}

// ServerToolUseBlock captures Anthropic's server_tool_use content block.
// Unlike a regular tool_use, the tool is invoked by Anthropic's backend
// (web search, code execution, etc.) and the invocation is already
// complete by the time the block reaches the client.
type ServerToolUseBlock struct {
	ID    string          `json:"id,omitempty"`
	Name  string          `json:"name,omitempty"`
	Input json.RawMessage `json:"input,omitempty"`
}

// ServerToolResultBlock captures the result of a server-side tool
// invocation (web_search_tool_result, code_execution_tool_result). The
// content field mirrors tool_result.content — Anthropic returns either a
// text string or an array of sub-blocks.
type ServerToolResultBlock struct {
	ToolUseID string          `json:"tool_use_id,omitempty"`
	Content   json.RawMessage `json:"content,omitempty"`
	IsError   *bool           `json:"is_error,omitempty"`

	// BlockType preserves the exact Anthropic wire type the result arrived as
	// ("web_search_tool_result", "code_execution_tool_result", …). The
	// outbound layer uses it to re-emit the correct block type when
	// forwarding to Anthropic. Empty string means the caller did not know
	// the upstream type and the outbound should default to
	// "web_search_tool_result" (Anthropic's original server-tool result).
	BlockType string `json:"-"`
}

// ImageURL represents an image URL with optional detail level.
type ImageURL struct {
	// URL is the URL of the image.
	URL string `json:"url"`

	// Specifies the detail level of the image. Learn more in the
	// [Vision guide](https://platform.openai.com/docs/guides/vision#low-or-high-fidelity-image-understanding).
	//
	// Any of "auto", "low", "high".
	Detail *string `json:"detail,omitempty"`
}

type Audio struct {
	// The format of the encoded audio data. Currently supports "wav" and "mp3".
	//
	// Any of "wav", "mp3".
	Format string `json:"format"`

	// Base64 encoded audio data.
	Data string `json:"data"`
}

type File struct {
	// The filename of the file.
	Filename string `json:"filename"`
	// The base64 encoded data of the file.
	FileData string `json:"file_data"`
	// FileID is OpenAI's uploaded-file handle ("file-abc123"). When set,
	// Responses outbound emits `{type:"input_file", file_id:...}` without
	// touching Filename / FileData. O-H6.
	FileID string `json:"file_id,omitempty"`
	// FileURL points at an externally-hosted file that the provider fetches
	// itself. O-H6.
	FileURL string `json:"file_url,omitempty"`
}
