package model

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

// Tool represents a function tool.
type Tool struct {
	// Type is the type of the tool.
	// Any of "function", "image_generation".
	Type            string           `json:"type"`
	Function        Function         `json:"function"`
	ImageGeneration *ImageGeneration `json:"image_generation,omitempty"`

	// CacheControl is used for provider-specific cache control (e.g., Anthropic).
	// This field is not serialized in JSON.
	CacheControl *CacheControl `json:"-"`

	// AnthropicServerSpec preserves the raw JSON for Anthropic server-side
	// tools (web_search_*, code_execution_*, computer_*). The outbound
	// Anthropic transformer reconstructs the wire payload from this raw body
	// so upstream-specific fields (max_uses, allowed_domains, display_*,
	// etc.) survive cross-tranformer round-trips without enumerating every
	// spec variant. Not serialized on the internal request.
	AnthropicServerSpec json.RawMessage `json:"-"`
}

// CacheControl represents cache control configuration.
// Shared by Anthropic prompt caching (`{"type":"ephemeral","ttl":"5m"|"1h"}`) and any future
// providers that piggyback on the same shape. The struct is serialized so internal logs and
// tests can snapshot it; outbound transformers decide whether to forward it.
type CacheControl struct {
	Type string `json:"type,omitempty"`
	TTL  string `json:"ttl,omitempty"`
}

// CacheControlType and CacheControlTTL values currently accepted by Anthropic's Messages API.
// Keep as typed constants so typos fail at compile time; unknown values should still be
// rejected at the inbound boundary.
const (
	CacheControlTypeEphemeral = "ephemeral"
	CacheTTL5m                = "5m"
	CacheTTL1h                = "1h"
)

// AnthropicMaxCacheBreakpoints is the provider-enforced upper bound on `cache_control` breakpoints
// per Messages request. Excess breakpoints must be pruned by the outbound layer rather than
// surfacing an HTTP 400 to the caller.
const AnthropicMaxCacheBreakpoints = 4

// Validate returns an error if the CacheControl values are not acceptable for Anthropic.
// Nil receivers are treated as valid (absent).
func (c *CacheControl) Validate() error {
	if c == nil {
		return nil
	}
	if c.Type != "" && c.Type != CacheControlTypeEphemeral {
		return fmt.Errorf("invalid cache_control.type %q (only %q is supported)", c.Type, CacheControlTypeEphemeral)
	}
	if c.TTL != "" && c.TTL != CacheTTL5m && c.TTL != CacheTTL1h {
		return fmt.Errorf("invalid cache_control.ttl %q (only %q or %q are supported)", c.TTL, CacheTTL5m, CacheTTL1h)
	}
	return nil
}

// Function represents a function definition.
type Function struct {
	Name        string          `json:"name"`
	Description string          `json:"description,omitempty"`
	Parameters  json.RawMessage `json:"parameters"`
	Strict      *bool           `json:"strict,omitempty"`
}

// FunctionCall represents a function call (deprecated).
type FunctionCall struct {
	// The name of the function to call.
	Name string `json:"name"`

	// Namespace preserves the Responses API namespace extension internally.
	// Chat Completions does not accept this field, so it must never be emitted
	// through the shared JSON representation.
	Namespace string `json:"-"`

	// The arguments to call the function with, as generated by the model in JSON
	// format. Note that the model does not always generate valid JSON, and may
	// hallucinate parameters not defined by your function schema. Validate the
	// arguments in your code before calling your function.
	Arguments string `json:"arguments"`
}

// ToolCall represents a tool call in the response.
type ToolCall struct {
	ID string `json:"id,omitempty"`

	// The type of the tool. Currently, only `function` is supported.
	Type string `json:"type,omitempty"`

	Function FunctionCall `json:"function"`

	// Index is the index of the tool call in the list of tool calls.
	// Cannot use omitempty, as an index of 0 would be omitted, which can break consumers.
	Index int `json:"index"`

	// ThoughtSignature preserves Gemini's per-functionCall thoughtSignature so
	// multi-turn tool use can be replayed without losing the provider-required
	// signature binding. Help field only; never serialized to client JSON.
	ThoughtSignature string `json:"-"`

	// ProviderExtensions stores provider-specific tool-call hints. It is internal-only.
	ProviderExtensions *ProviderExtensions `json:"-"`

	// CacheControl is used for provider-specific cache control (e.g., Anthropic).
	CacheControl *CacheControl `json:"-"`
}

type ToolFunction struct {
	Name string `json:"name"`
}

// ToolChoice represents the tool choice parameter for function calling.
//
// Tool choice can be a string or a struct.
type ToolChoice struct {
	ToolChoice      *string          `json:"tool_choice,omitempty"`
	NamedToolChoice *NamedToolChoice `json:"named_tool_choice,omitempty"`
}

// NamedToolChoice is the structured form of tool_choice. It covers both the
// OpenAI-shaped `{type:"function", function:{name:"..."}}` payload and the
// Anthropic-shaped `{type:"tool"|"any"|"none", name:"...",
// disable_parallel_tool_use:true}` variants so the internal model is lossless
// across providers.
type NamedToolChoice struct {
	// Type selects the variant. Values used across providers:
	//   - OpenAI: "function"
	//   - Anthropic: "auto" | "any" | "none" | "tool"
	// The string mode ("auto"/"required"/"none") is still carried on
	// ToolChoice.ToolChoice; this struct form is for the rich variants.
	Type string `json:"type"`

	// Function mirrors the OpenAI-style payload. Optional: Anthropic-style
	// variants (any / none / tool) either omit this entirely or use Name
	// instead, so callers must nil-check before reading Function.Name.
	Function *ToolFunction `json:"function,omitempty"`

	// Name carries Anthropic's top-level `name` field when Type is "tool".
	// Also populated for OpenAI-style to mirror Function.Name so downstream
	// emitters can rely on a single field.
	Name *string `json:"name,omitempty"`

	// DisableParallelToolUse surfaces Anthropic's
	// `disable_parallel_tool_use` flag. When true the provider is asked to
	// emit at most one tool call per turn, regardless of Type.
	DisableParallelToolUse *bool `json:"disable_parallel_tool_use,omitempty"`
}

// ResolvedFunctionName returns the tool name to force, preferring the top
// level Name field (Anthropic wire shape) and falling back to Function.Name
// (OpenAI wire shape). An empty string means no specific tool was pinned.
func (n *NamedToolChoice) ResolvedFunctionName() string {
	if n == nil {
		return ""
	}
	if n.Name != nil && strings.TrimSpace(*n.Name) != "" {
		return strings.TrimSpace(*n.Name)
	}
	if n.Function != nil {
		return strings.TrimSpace(n.Function.Name)
	}
	return ""
}

func (t ToolChoice) MarshalJSON() ([]byte, error) {
	if t.ToolChoice != nil {
		return json.Marshal(t.ToolChoice)
	}

	return json.Marshal(t.NamedToolChoice)
}

func (t *ToolChoice) UnmarshalJSON(data []byte) error {
	var str string

	err := json.Unmarshal(data, &str)
	if err == nil {
		t.ToolChoice = &str
		return nil
	}

	var named NamedToolChoice

	err = json.Unmarshal(data, &named)
	if err == nil {
		t.NamedToolChoice = &named
		return nil
	}

	return errors.New("invalid tool choice type")
}
